version: "3.9"

services:
  api:
    container_name: api
    image: entrega
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=gianr
      - DB_PASSWORD=91300962
      - DB=products_management
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn start'
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gianr
      - POSTGRES_PASSWORD=91300962
      - POSTGRES_DB=products_management
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
